### ISSUE TITLE
您好 我是来请教问题的  不知道在哪给你发消息 抱歉了

### ISSUE THREAD

**Issue by LiycJia** [crossle/VitamioMediaPlayerDemo#4]
E/Vitamio[Player]: [h264 @ 0xab537c80] AVC: nal size 1975
E/Vitamio[Player]: [h264 @ 0xab537c80] AVC: nal size 1975
E/Vitamio[Player]: [h264 @ 0xab537c80] no frame!
D/Vitamio[Player]: playback complete (0, 0)

在用vitamio的时候  出现这个问题  我播放的是本地下载的视频  为什么会出现这个的  有什么解决办法么？十分抱歉在这打扰您了  还希望您抽空能回一下  谢谢了  万分感激

**Comment by crossle** [comment]
这个是检测到没有视频然后播放结束了，可以联系一下官方的人，让他们看看

**Comment by LiycJia** [comment]
好的吧  那谢谢了
